/*
    File:    lynx_scaner_keyword_table.cpp
    Created: 09 February 2019 at 15:18 Moscow time
    Author:  Гаврилов Владимир Сергеевич
    E-mails: vladimir.s.gavrilov@gmail.com
             gavrilov.vladimir.s@mail.ru
             gavvs1977@yandex.ru
*/

#include "../include/lynx_scaner_keyword_table.h"

namespace lynx_scanner{
    const trans_table::Elem<Lexem_code> keywords_jump_table[] = {
        {const_cast<char32_t*>(U"ео"),   Lexem_code::Id,                 1}, // 0:   б...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,                 3}, // 1:   бе...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                 4}, // 2:   бо...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,                 5}, // 3:   без...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,                 6}, // 4:   бол...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                 7}, // 5:   безз...
        {const_cast<char32_t*>(U"ш"),    Lexem_code::Id,                 8}, // 6:   боль...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_bezzn,           9}, // 7:   беззн...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                13}, // 8:   больш...
        {const_cast<char32_t*>(U"26"),   Lexem_code::Id,                14}, // 9:   беззн1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                16}, // 10:  беззн3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                17}, // 11:  беззн6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bezzn8,          0}, // 12:  беззн8
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                18}, // 13:  большо...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                19}, // 14:  беззн12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bezzn16,         0}, // 15:  беззн16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bezzn32,         0}, // 16:  беззн32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bezzn64,         0}, // 17:  беззн64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bolshoe,         0}, // 18:  большое
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bezzn128,        0}, // 19:  беззн128

        {const_cast<char32_t*>(U"еоы"),  Lexem_code::Id,                21}, // 20:  в...
        {const_cast<char32_t*>(U"чщ"),   Lexem_code::Id,                24}, // 21:  ве...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,                26}, // 22:  во...
        {const_cast<char32_t*>(U"бдй"),  Lexem_code::Id,                27}, // 23:  вы...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                30}, // 24:  веч...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_veshch,         31}, // 25:  вещ...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                35}, // 26:  воз...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                36}, // 27:  выб...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                37}, // 28:  выд...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                38}, // 29:  вый...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                39}, // 30:  вечн...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                40}, // 31:  вещ1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                41}, // 32:  вещ3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                42}, // 33:  вещ6...
        {const_cast<char32_t*>(U"0"),    Lexem_code::Id,                43}, // 34:  вещ8...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                44}, // 35:  возв...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                45}, // 36:  выбе...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                46}, // 37:  выде...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                47}, // 38:  выйд...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vechno,          0}, // 39:  вечно
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                48}, // 40:  вещ12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch32,        0}, // 41:  вещ32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch64,        0}, // 42:  вещ64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch80,        0}, // 43:  вещ80
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                49}, // 44:  возвр...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                50}, // 45:  выбер...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                51}, // 46:  выдел...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vyjdi,           0}, // 47:  выйди
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch128,       0}, // 48:  вещ128
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                52}, // 49:  возвра...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vyberi,          0}, // 50:  выбери
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                53}, // 51:  выделе...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vozvrat,         0}, // 52:  возврат
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                54}, // 53:  выделен...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                55}, // 54:  выделени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vydelenie,       0}, // 55:  выделение

        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                57}, // 56:  г...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                58}, // 57:  го...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                59}, // 58:  гол...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                60}, // 59:  голо...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                61}, // 60:  голов...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                62}, // 61:  головн...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,                63}, // 62:  головна...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_golovnaya,       0}, // 63:  головная

        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                65}, // 64:  д...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,                66}, // 65:  дл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_dlya,            0}, // 66:  для

        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                68}, // 67:  е...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                69}, // 68:  ес...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                70}, // 69:  есл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_esli,            0}, // 70:  если

        {const_cast<char32_t*>(U"нс"),   Lexem_code::Id,                72}, // 71:  и...
        {const_cast<char32_t*>(U"ае"),   Lexem_code::Id,                74}, // 72:  ин...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                76}, // 73:  ис...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,                77}, // 74:  ина...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                78}, // 75:  ине...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                79}, // 76:  ист...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                80}, // 77:  инач...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ines,            0}, // 78:  инес
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                81}, // 79:  исти...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_inache,          0}, // 80:  иначе
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                82}, // 81:  истин...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_istina,          0}, // 82:  истина

        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                84}, // 83:  к...
        {const_cast<char32_t*>(U"мн"),   Lexem_code::Id,                85}, // 84:  ко...
        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,                87}, // 85:  ком...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                88}, // 86:  кон...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                89}, // 87:  комп...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                90}, // 88:  конс...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_kompl,          91}, // 89:  компл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_konst,           0}, // 90:  конст...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                95}, // 91:  компл1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                96}, // 92:  компл3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                97}, // 93:  компл6...
        {const_cast<char32_t*>(U"0"),    Lexem_code::Id,                98}, // 94:  компл8...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                99}, // 95:  компл12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl32,         0}, // 96:  компл32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl64,         0}, // 97:  компл64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl80,         0}, // 98:  компл80
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl128,        0}, // 99:  компл128

        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               101}, // 100: л...
        {const_cast<char32_t*>(U"гж"),   Lexem_code::Id,               102}, // 101: ло...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_log,           104}, // 102: лог...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,               108}, // 103: лож...
        {const_cast<char32_t*>(U"6"),    Lexem_code::Id,               109}, // 104: лог1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               110}, // 105: лог3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,               111}, // 106: лог6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_log8,            0}, // 107: лог8
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_lozh,            0}, // 108: ложь
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_log16,           0}, // 109: лог16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_log32,           0}, // 110: лог32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_log64,           0}, // 111: лог64

        {const_cast<char32_t*>(U"ао"),   Lexem_code::Id,               113}, // 112: м...
        {const_cast<char32_t*>(U"лс"),   Lexem_code::Id,               115}, // 113: ма...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               117}, // 114: мо...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               118}, // 115: мал...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               119}, // 116: мас...
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               120}, // 117: мод...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               121}, // 118: мале...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               122}, // 119: масс...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               123}, // 120: моду...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,               124}, // 121: мален...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               125}, // 122: масси...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,               126}, // 123: модул...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               127}, // 124: малень...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_massiv,          0}, // 125: массив
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_modul,           0}, // 126: модуль
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               128}, // 127: маленьк...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               129}, // 128: маленько...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_malenkoe,        0}, // 129: маленькое

        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               131}, // 130: н...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,               132}, // 131: ни...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               133}, // 132: нич...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               134}, // 133: ничт...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_nichto,          0}, // 134: ничто

        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               136}, // 135: о...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               137}, // 136: ос...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               138}, // 137: осв...
        {const_cast<char32_t*>(U"б"),    Lexem_code::Id,               139}, // 138: осво...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               140}, // 139: освоб...
        {const_cast<char32_t*>(U"ж"),    Lexem_code::Id,               141}, // 140: освобо...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               142}, // 141: освобож...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               143}, // 142: освобожд...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               144}, // 143: освобожде...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               145}, // 144: освобожден...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               146}, // 145: освобождени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_osvobozhdenie,   0}, // 146: освобождение...

        {const_cast<char32_t*>(U"ео"),   Lexem_code::Id,               148}, // 147: п...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               150}, // 148: пе...
        {const_cast<char32_t*>(U"вк"),   Lexem_code::Id,               151}, // 149: по...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               153}, // 150: пер...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               154}, // 151: пов...
        {const_cast<char32_t*>(U"ау"),   Lexem_code::Id,               155}, // 152: пок...
        {const_cast<char32_t*>(U"мч"),   Lexem_code::Id,               157}, // 153: пере...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               159}, // 154: повт...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_poka,            0}, // 155: пока
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               160}, // 156: поку...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perem,           0}, // 157: перем
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               161}, // 158: переч...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               162}, // 159: повто...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               163}, // 160: покуд...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               164}, // 161: перечи...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               165}, // 162: повтор...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_pokuda,          0}, // 163: покуда
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               166}, // 164: перечис...
        {const_cast<char32_t*>(U"й"),    Lexem_code::Id,               167}, // 165: повторя...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               168}, // 166: перечисл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_povtoryaj,       0}, // 167: повторяй
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               169}, // 168: перечисле...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               170}, // 169: перечислен...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               171}, // 170: перечислени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perechislenie,   0}, // 171: перечисление

        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               173}, // 172: р...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,               174}, // 173: ра...
        {const_cast<char32_t*>(U"б"),    Lexem_code::Id,               175}, // 174: раз...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               176}, // 175: разб...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               177}, // 176: разбо...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_razbor,          0}, // 177: разбор

        {const_cast<char32_t*>(U"ист"),  Lexem_code::Id,               179}, // 178: с...
        {const_cast<char32_t*>(U"м"),    Lexem_code::Id,               182}, // 179: си...
        {const_cast<char32_t*>(U"ы"),    Lexem_code::Id,               183}, // 180: сс...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               184}, // 181: ст...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               185}, // 182: сим...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               186}, // 183: ссы...
        {const_cast<char32_t*>(U"оу"),   Lexem_code::Id,               187}, // 184: стр...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_simv,            0}, // 185: симв
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               189}, // 186: ссыл...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               190}, // 187: стро...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               191}, // 188: стру...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               192}, // 189: ссылк...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               193}, // 190: строк...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               194}, // 191: струк...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ssylka,          0}, // 192: ссылка
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_stroka,          0}, // 193: строка
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               195}, // 194: структ...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               196}, // 195: структу...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               197}, // 196: структур...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_struktura,       0}, // 197: структура

        {const_cast<char32_t*>(U"ио"),   Lexem_code::Id,               199}, // 198: т...
        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,               201}, // 199: ти...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_to,              0}, // 200: то
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tip,             0}, // 201: тип

        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               203}, // 202: ф...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               204}, // 203: фу...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               205}, // 204: фун...
        {const_cast<char32_t*>(U"ц"),    Lexem_code::Id,               206}, // 205: функ...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               207}, // 206: функц...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               208}, // 207: функци...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_funktsiya,       0}, // 208: функция

        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               210}, // 209: ц...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               211}, // 210: це...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_tsel,          212}, // 211: цел...
        {const_cast<char32_t*>(U"26"),   Lexem_code::Id,               216}, // 212: цел1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               218}, // 213: цел3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,               219}, // 214: цел6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel8,           0}, // 215: цел8
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,               220}, // 216: цел12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel16,          0}, // 217: цел16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel32,          0}, // 218: цел32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel64,          0}, // 219: цел64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel128,         0}, // 220: цел128

        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               222}, // 221: ч...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               223}, // 222: чи...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               224}, // 223: чис...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               225}, // 224: чист...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               226}, // 225: чиста...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_chistaya,        0}  // 226: чистая
    };
};